# Generated by Django 4.1.2 on 2022-10-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
