# Generated by Django 4.1.2 on 2022-10-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_human_role_id_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.role'),
            preserve_default=False,
        ),
    ]
