# Generated by Django 4.1.2 on 2022-10-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_human_email_human_password_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role'),
        ),
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('is_married', models.BooleanField()),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_deleted', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
        ),
    ]
