# Generated by Django 4.1.2 on 2022-10-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_human_role_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted',
            name='time_deleted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
